version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=web
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on: 
      - db
    networks:
      - app-network

  db:
    image: postgres:12-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_DB=web
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
